# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is emptied to resolve a collision with 0001_initial.
    """
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]
